version: '3'
services:

    nginx-1.10-be:
        image: maxnag/link-reduction-be:latest
        container_name: link-reduction-be
        restart: always
        ports:
            - 8080:80
        environment:
            VIRTUAL_HOST: localhost-be
        links:
            - php7.2-fpm
        working_dir: "/var/www/be"
        volumes:
            - link-reduction-be:/var/www/be:rw

    nginx-1.10-fe:
        image: maxnag/link-reduction-fe:latest
        container_name: link-reduction-fe
        restart: always
        ports:
            - 80:80
        environment:
            VIRTUAL_HOST: localhost-fe
        links:
            - php7.2-fpm
        working_dir: "/var/www/fe"
        volumes:
            - link-reduction-fe:/var/www/fe:rw

    chat:
        image: maxnag/link-reduction-fe:latest
        container_name: chat
        restart: always
        ports:
            - 90:90
        environment:
            VIRTUAL_HOST: chat-fe
        working_dir: "/var/www/chat"
        volumes:
            - chat-fe:/var/www/chat:rw

    mysql-5.6:
        image: maxnag/link-reduction-mysql:latest
        container_name: link-reduction-be-mysql
        restart: always
        ports:
            - 3307:3306
        volumes:
            - db-data:/docker-entrypoint-initdb.d

    php7.2-fpm:
        image: maxnag/link-reduction-php:latest
        container_name: link-reduction-be-php
        restart: always
        environment:
            TERM: xterm
            XDEBUG_CONFIG: remote_host=localhost
        working_dir: "/var/www/be"
        volumes:
            - link-reduction-be:/var/www/be:rw
        links:
            - mysql-5.6

volumes:
    db-data:
        external: false
    link-reduction-be:
        external: false
    link-reduction-fe:
        external: false
    chat-fe:
        external: false
