version: '3'
services:

    nginx-1.10-be:
        image: maxnag/smsedge-be:files
        container_name: smsedge-be
        restart: always
        ports:
            - 8080:80
        environment:
            VIRTUAL_HOST: localhost-be
        links:
            - php7.2-fpm

    nginx-1.10-fe:
        image: maxnag/smsedge-fe:files
        container_name: smsedge-fe
        restart: always
        ports:
            - 80:80
        environment:
            VIRTUAL_HOST: localhost-fe

    mysql-5.6:
        image: maxnag/smsedge-mysql:files
        container_name: smsedge-be-mysql
        restart: always
        ports:
            - 3307:3306

    php7.2-fpm:
        image: maxnag/smsedge-be-php:files
        container_name: smsedge-be-php
        restart: always
        environment:
            TERM: xterm
            XDEBUG_CONFIG: remote_host=localhost
        links:
            - mysql-5.6